server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
      url: jdbc:mysql://localhost:3306/leyou
      username: root
      password: root
  jackson:
    default-property-inclusion: non_null  # json处理时忽略空值

#注册微服务到eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
mybatis:
  type-aliases-package: com.leyou.pojo
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql语句
      map-underscore-to-camel-case: true # 驼峰配置
# 秘钥的相关配置
ly:
  jwt:
    pubKeyPath: E:\\imags\\rsa.pub          # 公钥地址
    cookieName: LY_TOKEN                    # cookie的名称
  worker:                         #推特的雪花算法 给每个部署的节点都配置机器id
    workerId: 1
    datacenterId: 1
  pay: #
      appID: wx8397f8696b538317  #公众账号ID
      mchID: 1473426802          # 商户号
      key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb #生成签名的秘钥 该签名不是随意写的 ，而是在微信公号上生成的
      httpConnectTimeoutMs: 1000 #连接超时时间
      httpReadTimeoutMs: 8000    #读取超时时间
      tradeType: NATIVE          #交易类型 NATIVE表示扫描支付
      spbillCreateIp: 127.0.0.1
      notifyUrl: http://e52ppi.natappfree.cc/notify/wxpay  # 下单成功通知回调地址 必须是外网