server:
  port: 8085

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:            # 不要忘记在引入rabbitmq依赖后，对rabbitmq进行配置
    host: 192.168.86.138
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:
        enabled: true             # 默认false
        initial-interval: 10000ms # 默认10000ms
        max-interval: 30000ms     # 默认10000ms
        multiplier:  1            # 默认2
        exchange: ly.item.exchange
    publisher-confirms: true      #生产者确认机制 默认false
  redis:
    host: 192.168.86.138

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo
  configuration:
    map-underscore-to-camel-case: true  # 命名驼峰