server:
  port: 8083  # 配置服务端口号
spring:
  application:
    name: es-search-service  # 配置服务名称
  data:
    elasticsearch:            # 配置es连接信息
      cluster-name: elasticsearch
      cluster-nodes: 192.168.86.138:9300
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  rabbitmq:              #mq消费者配置
    host: 192.168.86.138
    username: leyou
    password: leyou
    virtual-host: /leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5     # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期