#设置服务的端口
server:
  port: 10010

#设置服务名称
spring:
  application:
    name: api-gateway

#注册eureka服务(为了从eureka中拉取服务列表)
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5  # 每5秒拉取一次服务列表 默认30s

zuul:
  prefix: /api  # 添加路由前缀
  routes:
    item-service: /item/**    # 商品微服务的路由配置,凡是以/item开头的请求都会经过路由处理
    upload-service:           # 图片上传微服务路由配置
      path: /upload/**
      servicId: upload-service
      strip-prefix: false
    es-search-service: /search/**   # ES微服务路由配置
    user-service:      /user/**     # 用户中心微服务
    auth-service:     /auth/**     # 授权中心微服务
    cart-service:     /cart/**     # 购物车微服务
    order-service:     /order/**     # 订单微服务
  sensitive-headers:             # 把敏感头设置为null
  host:
    connect-timeout-millis: 100000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000
  add-host-header: true
    #socket超时        # 携带请求本身的head头信息

ribbon:
  ConnectTimeout: 1000          # ribbon连接超时时间(ms) 默认2000ms
  ReadTimeout: 3500             # ribbon读取数据超时时间(ms)   默认5000ms
  MaxAutoRetriesNextServer: 0   # 同一服务不同实例的重试次数（配置为0就不尝试重试） 默认1
  MaxAutoRetries: 0             # 同一实例的重试次数（配置为0表示不重试） 默认0

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 50000 # 熔断超时时长：5000ms 默认1000ms

# 秘钥的相关配置
ly:
  jwt:
    pubKeyPath: E:\\imags\\rsa.pub          # 公钥地址
    cookieName: LY_TOKEN                    # cookie的名称
  filter:                                   # zuul过滤器要放行的白名单接口
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
      - /api/cart
      - /api/order