#设置服务的端口
server:
  port: 8081

spring:
  application:
    name: item-service   #设置服务名称
  datasource:            #设置数据库连接池（会根据url自动识别使用驱动,故无需在此处配置数据库驱动）
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
  rabbitmq:             #rabbitmq的相关配置
      host: 192.168.86.138
      username: leyou
      password: leyou
      virtual-host: /leyou
      template:
        retry:
          enabled: true             # 默认false
          initial-interval: 10000ms # 默认10000ms
          max-interval: 30000ms     # 默认10000ms
          multiplier:  1            # 默认2
        exchange: ly.item.exchange
      publisher-confirms: true      #生产者确认机制 默认false
#注册微服务到eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
      lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

# 打印sql语句
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 驼峰配置
